OnlineExamination::Application.routes.draw do
  resources :test_users

  #Routes generated by devise
  devise_for :users

  
  #get "welcome/index"
  
  resources :exams do
    resources :questions  
  end
   
  root to: "exams#index"


  namespace :u do
    get 'exam/:id/take' => 'exams#question'
    get 'exam/:id/question/:qindex', controller: 'exams', action: 'question'
    post 'exam/:id/answer', controller: 'exams', action: 'answer'
    get 'exam/:id/result' => 'exams#result'
  end

end
